### ISSUE TITLE
Clean and finalize Equity program

### ISSUE THREAD

**Issue by sdiby** [NeighborhoodInfoDC/Equity#19]
- All final data sets should be labeled (the data set itself labeled and all variables labelled) and registered with the metadata system (with the exception of comms output files)
- Remove decimal calculations and any other unnecessary process
- Review and standardize file naming conventions across files. (profile_tabs_acs, etc.)

**Comment by lhendey** [comment]
@sdiby - i merged and committed changes today to branch 19 - be sure to sync when you next work on it.

**Comment by lhendey** [comment]
@sdiby Closing issue!
