### ISSUE TITLE
Create Summary Data for Neighborhood Cluster, ward and city

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/Equity#2]
From the ACS 2010-14 create summary indicators at the ward, cluster and city levels.

**Comment by lhendey** [comment]
@sdiby for Stage 3 use this file: Equity/Prog/Compile_ACS_for_profile.sas

**Comment by lhendey** [comment]
@sdiby  - will you create a new branch called develop_#2 for this issue?

**Comment by lhendey** [comment]
@sdiby - I got the race info I need. The libnames needed to be pointing to the equity library. You can review the changes I made to see the other small fixes.  Let me look at the MOEs and let you know which categories to use for the final set of variables.

**Comment by sdiby** [comment]
@lhendey thank you for working through that. I'm ready to input the additional variables whenever you're ready.

**Comment by lhendey** [comment]
You should fix the labels on the alone variables. Could you add the pct poverty by race (all options ) and run a similar proc print to the one I did and send it to me?

**Comment by sdiby** [comment]
I've fixed the variables and will have the pct poverty by race to you shortly

**Comment by sdiby** [comment]
@lhendey 

I figured out why foreign and native born education indicators aren't appearing. Currently the IF statements in the final data step in the Equity transpose program distinguish the variable suffixes "FB_2010_14" and "NB_2010_14" from Black variables with the suffix "B_2010_14." But this causes the foreign and native born variables to disappear altogether from the output. 

The variables remain if I delete these IF statements, but then the output table populates these variables with values in the "black" column where there shouldn't be any.

Can we delete these IF statements and manually put in the right values in the output table's "black" column? Or do you have a better coding solution than what's currently there? 

Here's a bit of the code:
 if _name_ ="Gap25andOverWoutHSFB_2010_14" then do; black=0; category=.; end;
 if _name_ ="Pct25andOverWoutHSFB_2010_14" then do; black=0; category=.; end;
 if _name_ ="Pct25andOverWoutHSFB_m_2010_14" then do; black=0; category=.; end;

**Comment by lhendey** [comment]
@sdiby – I think since you have already ordered the variables- do we need the category flags anymore?

**Comment by sdiby** [comment]
If the category flags were only there to sort, then I don't think we need them anymore. I can go ahead and delete them if that's right--then we should have the right output.

**Comment by lhendey** [comment]
@sdiby Why don’t you just pull out that code and comment it out at the bottom
