### ISSUE TITLE
clean up labels and extra vars

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/Equity#25]
L:\Metadata\meta_equity.html

See for example: L:\Metadata\meta_equity_profile_acs_city.html

**Comment by lhendey** [comment]
@sdiby - please start a new branch #25.

**Comment by lhendey** [comment]
@rpitingolo this is still a valid issue.  There are a bunch of MOEs that are not labeled. 

I have from @sdiby (on 11/21/16)  I remember leaving those unlabeled after noticing that the moe_prop_a macro in the Equity_Compile_ACS_for_profile didn’t have a label parameter. I can plan to create those labels today. 

Somala - I'm assuming you didn't start on this.

**Comment by rpitingolo** [comment]
@lhendey @sdiby Thanks. Somala, please let me know if this is still on your radar or else I can reassign it once I see who's available.

**Comment by lhendey** [comment]
@rpitingolo - can you look into whether we can add the label parameter to %moe_prop_a ? cc @sdiby.

**Comment by rpitingolo** [comment]
Added label parameter to %moe_prop_a
