### ISSUE TITLE
Equity gap tables

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Equity#53]
@maggiesu0725 In addition to pulling the data for the equity feature, can we add a task to create a set of tables that show the equity gaps between different places? I'd like to see what the gaps look like across the board. It will be helpful in thinking about how to use the tool.

The idea would be, for each indicator, having a pair of tables that look like this.

```
People above poverty

         DC    Ward 1   Ward 2   Ward 3  ...
DC       -     ...      ...      ...
Ward 1   ...   -        ...      ...
Ward 2   ...   ...      -        ...
Ward 3   ...   ...      ...      -
...
```

We would have a similar table for the neighborhood clusters. 

The rows can be the focus geography, and the columns the comparison geography. The values in the table cells would be the gap amount, that is, the number of people, adults, children, etc., in the focus geography who need to change their condition to have equity with the comparison geography. Although we wouldn't show this in the tool, we should include negative gaps in the table (i.e., target geos where people are better off than in the comparison geo). 

I'd like these tables in an Excel Workbook (or two Excel workbooks, if we want to separate wards and clusters that way). We can then use conditional formatting to highlight the positive and negative gaps. 

Let me know how this sounds. This task should not take priority over completing the data for the development team by this Friday. Thanks!  cc: @lhendey

**Comment by ptatian** [comment]
@maggiesu0725 It came up in today's demo discussion that we might need to create some "findings" from the DC equity indicator tool data. These tables would be useful for doing that. Is this something you can take a look at next week?

**Comment by maggiesu0725** [comment]
Sure. @ptatian
