### ISSUE TITLE
Pull CRA small business lending data for JPMC equity feature

### ISSUE THREAD

**Issue by maggiesu0725** [NeighborhoodInfoDC/Equity#55]

**Comment by ptatian** [comment]
@maggiesu0725 My search was inconclusive on the small business sizes. My inclination is to agree that 20 employees is too small. Unless they had some good reason for using that cutoff, I would go with something more like 50. cc: @lhendey

**Comment by maggiesu0725** [comment]
@ptatian @lhendey  thank you I will use 50.

**Comment by maggiesu0725** [comment]
@ptatian  so 17 tracts are still missing data for loan amounts after calculating 3 year average, and if we drop the tracts that have less than 50 employees in small businesses that has less than 50 employees, we will have 35 tracts that are missing this measure, which is a lot. I suggest since we are using three year average, we will not drop tracts with less than 50 employees because the numerator(loan amount) for those tracts will reflect the small number of SB employees

**Comment by ptatian** [comment]
@maggiesu0725 Right, but I think we said we were _not_ going to drop tracts with < 50 employees. You should calculate the cluster and ward summaries from the tracts and then, if any of those clusters or wards have fewer than 50 employees, you would drop them. Does that make sense?

**Comment by maggiesu0725** [comment]
yes, thank you. @ptatian
