### ISSUE TITLE
recalculate pct of homes sales affordable 

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/Equity#60]
@maggiesu0725 - can you recalculate the percent of sales affordable?

we want to use the average household income for people of color in dc. 

numerator =  aggregate income for everyone (agghshldincome_2012_16) - aggregate income for non-Hispanic whites (aggincomew_2012_16)

denominator = numhshlds_2012_16 - numhshldsw_2012_16

Then plug in the average household income into the program Equity_Compile_Feature_Data.sas where you are current using the DC median household income. 

Rerun. 

Make sense?

**Comment by maggiesu0725** [comment]
sure @lhendey
