### ISSUE TITLE
add broadband internet subscription to equity indicators for on line tool 

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/Equity#71]
Project Code: 101419-0002-001-00099

Percent of Households with a Broadband Subscription:
      pctbroadband= Numbroadband_&year./Numhhdefined_&year. ;

@maggiesu0725 - can you rerun all the ACS variables for 2013-17? Please change the output so we don't over-write the old files. We want to hand over everything to Alice in the same format as last time.

**Comment by maggiesu0725** [comment]
L:\Libraries\Equity\Prog\Equity_Compile_Feature_Data.log
